INSERT INTO template (id, title, detail, content, owner_id, team_id, editable, last_amend_date) VALUES
(1, 'Welcome Email', 'Template for welcoming new users', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Welcome to our service! We are glad to have you."}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 1, 1, TRUE, '2025-02-16 10:00:00'),
(2, 'Password Reset', 'Template for password reset instructions', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"You requested a password reset. "}]},{"type":"paragraph","content":[{"type":"text","text":"Click the link below to reset your password:"}]},{"type":"paragraph","content":[{"type":"text","text":"{{reset_link}}"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 2, 1, TRUE, '2025-02-16 11:00:00'),
(3, 'Account Activation', 'Template for account activation', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Please activate your account by clicking the link below:"}]},{"type":"paragraph","content":[{"type":"text","text":"{{activation_link}}"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 3, 2, FALSE, '2025-02-16 12:00:00'),
(4, 'Newsletter', 'Template for monthly newsletter', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Here is our monthly newsletter."}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 4, 3, TRUE, '2025-02-16 13:00:00'),
(5, 'Promotion', 'Template for promotional emails', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"We have a special promotion for you. Check it out!"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 5, 4, FALSE, '2025-02-16 14:00:00'),
(6, 'Feedback Request', 'Template for requesting feedback', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"We would love to hear your feedback. Please fill out the survey below:"}]},{"type":"paragraph","content":[{"type":"text","text":"{{survey_link}}"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 1, 5, TRUE, '2025-02-16 15:00:00'),
(7, 'Event Invitation', 'Template for event invitations', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"You are invited to our upcoming event. Please RSVP below:"}]},{"type":"paragraph","content":[{"type":"text","text":"{{rsvp_link}}"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 2, 2, FALSE, '2025-02-16 16:00:00'),
(8, 'Service Update', 'Template for service updates', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"We have an important update regarding our service."}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 3, 3, TRUE, '2025-02-16 17:00:00'),
(9, 'Account Deactivation', 'Template for account deactivation', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Your account will be deactivated soon. If this is a mistake, please contact us."}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 4, 4, FALSE, '2025-02-16 18:00:00'),
(10, 'Thank You', 'Template for thank you emails', '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"Dear {{name}},"}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Thank you for being a valued customer."}]},{"type":"paragraph"},{"type":"paragraph","content":[{"type":"text","text":"Best regards,"}]},{"type":"paragraph","content":[{"type":"text","text":"The Team"}]}]}', 5, 5, TRUE, '2025-02-16 19:00:00');